version : "3.8" # Versi贸n de Docker Compose
services:
  api_cursos: # Servicio de la API de cursos
    build: # Construcci贸n de la imagen
      context: . # Contexto de construcci贸n
      dockerfile: Dockerfile # Dockerfile a utilizar
    ports: # Puertos a exponer
      - "8083:8083"
    env_file:
      - .env # Archivo de variables de entorno
    command: ["java", "-jar", "/cursos_app/cursos_app.jar"] # Comando para ejecutar la aplicaci贸n